### ISSUE TITLE
Default descriptor initialization (and discussion of C vs C++ callbacks)

### ISSUE THREAD

**Issue by mrshannon** [webgpu-native/webgpu-headers#158]
Many of the descriptors in WebGPU have default values, and more importantly default values which are not 0 and so a simple `memset` or zero initialization is not appropriate.

An example of what does not work
```c
WGPUTextureDataLayout TextureDataLayout = {0};
TextureDataLayout.bytesPerRow = 512;
```
In this case `rowsPerImage = 0` instead of `WGPU_COPY_STRIDE_UNDEFINED`. 

Therefore, I propose adding default initialization defines to `webgpu.h`. While it is possible for each user to create their own, there are some benefits to implementing this in `webgpu.h`:

- Adding fields later with default values to descriptors does not introduce undefined behavior in existing code.
- It is possible to change default values later without breaking existing code (while `WGPU_COPY_STRIDE_UNDEFINED` fixes this, many defaults do not have a define as they are simply 0).
- One source of truth

One way to implement this is to add defines for each descriptor:
```c
#define WGPUTextureDataLayout_DEFAULT { NULL, 0, WGPU_COPY_STRIDE_UNDEFINED, WGPU_COPY_STRIDE_UNDEFINED }
```

This would allow users to write:
```c
WGPUTextureDataLayout TextureDataLayout = WGPUTextureDataLayout_DEFAULT;
TextureDataLayout.bytesPerRow = 512;
```

---

TODO list:

- [ ] Don't forget to write compile tests for these! #240

**Comment by grovesNL** [comment]
This sounds reasonable to me. We use defaults for a lot of types in `wgpu` and find it really useful, e.g. `PrimitiveState` https://github.com/gfx-rs/wgpu/blob/77b2c25684f971daa977596403f01c71d32ea685/wgpu/examples/msaa-line/main.rs#L65-L69

**Comment by mrshannon** [comment]
> Also @mrshannon, you could use the C++ headers generated by Dawn, they have default initialization for the various structs.

Sort of off topic, but we were initially using the C++ headers but dropped them for the C headers as we kept having to cast everywhere because the callbacks always use the C types and not the C++ types. But that came with it's own issues (`WGPUBufferUsage` vs `WGPUBufferUsageFlags`), maybe it's time to consider switching back.

**Comment by Kangz** [comment]
Any idea on how to improve WGPUBufferUsage vs. WGPUBufferUsageFlags?

For the C++ header typedefs I'm not sure how to fix it because technically the signatures of the functions are different so if we want UBSan to be happy we would need to make an indirection (and allocation).

**Comment by mrshannon** [comment]
> Any idea on how to improve WGPUBufferUsage vs. WGPUBufferUsageFlags?

You technically don't need `WGPUBufferUsageFlags` as `WGPUBufferUsage` will always be wide enough for the bitwise combination because we have `WGPUBufferUsage_Force32 = 0x7FFFFFFF` which is effectively doing what is done for the C++ headers with:
```c++
enum class BufferUsage : uint32_t {
```

> For the C++ header typedefs I'm not sure how to fix it because technically the signatures of the functions are different

Correct, I don't think there is either, not without allocating a `std::function` on the heap and destroying it later (not a good idea). But what could be done is to make it clear (without looking at implementation files) that the C and C++ enums are safe to cast by providing a casting function. In our engine we do all kinds of seemingly "unsafe" casting but it is behind a type-trait like function which always performs the "safe" cast.

I am also not sure it makes sense to have:
```c++
using BufferMapCallback = WGPUBufferMapCallback;
```
Because without that it's at least clear the callbacks will always be using the C API.

But again, this is way off topic (with relation to the initial issue), so perhaps we should continue this somewhere else?

**Comment by kainino0x** [comment]
> You technically don't need `WGPUBufferUsageFlags` as `WGPUBufferUsage` will always be wide enough for the bitwise combination because we have `WGPUBufferUsage_Force32 = 0x7FFFFFFF` which is effectively doing what is done for the C++ headers with:

This is strictly true but in C++ we also have operator overloads so when you do `wgpu::BufferUsage::CopySrc | wgpu::BufferUsage::CopyDst` you get a `wgpu::BufferUsage` value. In C `WGPUBufferUsage_CopySrc | WGPUBufferUsage_CopyDst` will give you an int of some kind. So this would force callers of the API to cast back to the appropriate type.

```c
desc.usage = static_cast<WGPUBufferUsage>(WGPUBufferUsage_CopySrc | WGPUBufferUsage_CopyDst);
```

Apparently, the cast is only needed in C++, C seems happy without a cast. So I guess we could define operator overloads for these types behind `#ifdef __cplusplus`...?

**Comment by kainino0x** [comment]
I split the flags discussion out to #159, since it's mostly off-topic.

**Comment by Kangz** [comment]
@mrshannon we could have a `wgpu::FromC(...)` and `wgpu::ToC(...)` serie of functions that convert between the C and C++ datatypes. WDYT?

**Comment by mrshannon** [comment]
> @mrshannon we could have a `wgpu::FromC(...)` and `wgpu::ToC(...)` serie of functions that convert between the C and C++ datatypes. WDYT?

I think that's a good idea. Makes it clear without looking at the implementation that those casts are safe.

**Comment by kainino0x** [comment]
> For the C++ header typedefs I'm not sure how to fix it because technically the signatures of the functions are different so if we want UBSan to be happy we would need to make an indirection (and allocation).

This is kind of a dumb idea, but what if the C API had *two* userdata pointers, and the C++ wrapper used one for the C++ callback? I can imagine this being useful for other language bindings, as well. Would look vaguely like:

```c++
namespace wgpu {
    typedef void (*RequestDeviceCallback)(RequestDeviceStatus status, Device device,
            char const * message, void * userdata);

    void RequestDeviceWrapper(WGPURequestDeviceStatus status, WGPUDevice device,
            char const * message, void * userdata, void * binding_userdata) {
        RequestDeviceCallback callback = static_cast<RequestDeviceCallback>(binding_userdata);
        callback(static_cast<RequestDeviceStatus>(status), Device{device}, message, userdata);
    }
    void Adapter::RequestDevice(DeviceDescriptor const * descriptor, RequestDeviceCallback callback,
            void * userdata) const {
        wgpuAdapterRequestDevice(Get(), reinterpret_cast<WGPUDeviceDescriptor const * >(descriptor),
                RequestDeviceWrapper, reinterpret_cast<void * >(userdata), callback);
    }
}
```

**Comment by mrshannon** [comment]
Here is an example of [WebGPU INIT/NULL defines](https://gist.github.com/mrshannon/1217d98fd1d6455056fac0fb9215c048) we use for our project, pulled from our WebGPU utility library. It's not quite the same as the defaults in the C++ API provided by Dawn/Emscripten as it's defaults are based on the JS API and includes NULL initialization (which is required for some of the C structs). But it shows some the reasons why upstreaming this is preferred, differences between implementations which we had to paper over with defines.

**Comment by kainino0x** [comment]
I'm ever so slightly sad that our default structs aren't just all zeroes. I'm just spitballing - apparently this is the thread where I come up with silly C API ideas - but how awful would it be if instead of sentinel 0xFFFF_FFFF values we had a separate field to specify whether you've set the thing or not? (Basically a "type" field for whether it's undefined or int.)

This would also mean implementations must implement the same defaults that are specified in WebIDL, i.e. turning `_Undefined` values into their defaults, but I kinda think that is a good idea anyway.

**Comment by mrshannon** [comment]
> apparently this is the thread where I come up with silly C API ideas

I am honored to have started it.

> separate field to specify whether you've set the thing or not?

One option for this is for optional numbers the type could be changed to something like:
```c
strict OptionalUint32 {
    bool set;
    uint32_t value;
}
```
This way you could do:
```c
WGPUTextureViewDescriptor desc = {0};
desc.baseArrayLayer = {true, 4};
desc.arrayLayerCount = {true, 1};
```

It's interesting, and much more self documenting. But it does add quite a bit of complexity when setting optional numbers.

I think the bigger issue is with the nullable structs which are not NULL at the top but are NULL because something inside them is `_Undefined`. To me that is the bigger issue as it makes it very hard to understand what is going on. I think I would rather see something similar to `blend` in `WGPUColorTargetState` where the sub structure is given by pointer, as that is far more self documenting.

**Comment by kainino0x** [comment]
Something just occurred to me, which is that if we wanted zero initialization to give the default value then we'd need this {set, value} pattern not just for all of the number-or-undefined members, but also for all of the non-enum-type members that have non-zero default values in WebIDL (listed below). That would be kind of painful. The INIT structs are likely a better idea.

- mipLevelCount. don't want to make 0 mean "default value" unless the JS spec changes to make 0 an exception
- GPUTextureDescriptor.sampleCount, GPURenderPassLayout.sampleCount, GPUMultisampleState.count. same
- maxDrawCount. same
- GPUCanvasConfiguration.usage. same
- maxAnisotropy. same, or change JS spec to allow 0 (by clamping it to 1)
- lodMaxClamp. 0 is a valid value so it can't mean "default value"
- GPUMultisampleState.mask, GPUColorTargetState.writeMask, stencilReadMask, stencilWriteMask. same
- WGPUExtent3D.height/depthOrArrayLayers: just make these required in the C API

**Comment by kainino0x** [comment]
I assume you're asking about the C vs C++ callbacks specifically. I'm still working on a rework of the async APIs but the callback signature should be an orthogonal decision. I'll add it to the agenda but we won't meet until 2 weeks from now, so if folks on this thread + @rajveermalviya + @cwfitzgerald can chime in maybe we can agree on either:
- We keep it the way it is, C++ and other bindings will need an extra memory allocation somewhere to implement all of the callbacks (either one malloc/free per callback, or something cleverer)
- We add a second userdata pointer which should be enough for most cases (and when it isn't, bindings implementation can use an extra memory allocation)

**Comment by kainino0x** [comment]
(I'm in favor of the second userdata pointer)

**Comment by kainino0x** [comment]
The malloc/free (new/delete) version would look like this:

```cpp
namespace wgpu {
namespace {

struct RequestDeviceParameters {
    RequestDeviceCallback callback;
    void * userdata;
};

void RequestDeviceWrapper(WGPURequestDeviceStatus status, WGPUDevice device,
        char const * message, void * userdata) {
    RequestDeviceParameters* p = static_cast<RequestDeviceParameters*>(userdata);
    p->callback(static_cast<RequestDeviceStatus>(status), Device{device}, message, p->userdata);
    delete p;
}

}  // namespace

void Adapter::RequestDevice(DeviceDescriptor const * descriptor, RequestDeviceCallback callback,
        void * userdata) const {
    RequestDeviceParameters* p = new RequestDeviceParameters{callback, userdata};
    wgpuAdapterRequestDevice(Get(), reinterpret_cast<WGPUDeviceDescriptor const * >(descriptor),
            RequestDeviceWrapper, p);
}

}  // namespace wgpu
```

**Comment by rajveermalviya** [comment]
Other language bindings would definitely benefit from second userdata pointer, so +1 for that.

**Comment by kainino0x** [comment]
but no one was particularly opposed to adding the second userdata so if we think it's useful we should just add it.

In particular I'm thinking the C++ API _might_ want to keep both the lambda and raw-function interfaces, since raw-function will be faster.

**Comment by kainino0x** [comment]
We may also be able to make the raw-function version nicer to use by templating the userdata so it doesn't have to always be void*.

**Comment by beaufortfrancois** [comment]
It's great to see some activity in this space! 

FYI Here's the [Dawn bug](https://bugs.chromium.org/p/dawn/issues/detail?id=1892#c5).

**Comment by kainino0x** [comment]
I've been sketching out code in this gist:
https://gist.github.com/kainino0x/4f04609d91111b360cb4be93822b2f68

and have a new idea:
```c
    typedef void(*WGPUCallbackV)(WGPUSomething, size_t userdataSize, void* userdataPtr);
    void wgpuCallCallbackV(WGPUSomething, WGPUCallbackV, size_t userdataSize, void* userdataPtr);
```
The "V" is for "variable sized userdata". Instead of a single pointer, we take a whole array of raw data of variable size and we'll pass it back to you. This way the allocation is handled by the webgpu.h implementation and it may be able to do it more intelligently than just `new`/`delete`.

**Comment by kainino0x** [comment]
@kangz on the dawn issue:
> What about alignment constraints of the copied userdata in this case? It seems a bit overkill to have a variable sized userdata when using the API in C but it could be useful for other bindings and is a more general solution. So IDK :/

Probably we can just provide a large alignment guarantee. `alignof(std::max_align_t)` (or naive `malloc`) seems to be the way.

**Comment by kainino0x** [comment]
meeting: discussed this and it would be best to provide support for larger alignments than max_align_t. It's possible for the C++ bindings to detect an underaligned allocation and reallocate with logic like:
```c++
if constexpr (alignof(T) > alignof(max_align_t)) {
    if (reinterpret_cast<uintptr_t>(userdataPtr) % alignof(T) != 0) {
        reallocate
    }
}
```
And it's also possible to `static_assert(alignof(T) <= alignof(max_align_t))`.
But better just make the C API do it for us. I've updated the gist.

Still, didn't come to a conclusion yet on whether this is better than just making the bindings responsible for the allocation.

**Comment by kainino0x** [comment]
@cwfitzgerald also raised a question about whether it's even valid to be memcpying a lambda around. I tried to research this and found that it's probably fine if it's is_trivially_copyable, but otherwise I can't find an answer. We'd need to move the object into C's raw memory and then move it back out later, which I don't know how to do in C++. And on top of that I'm not sure whether it's valid to memcpy it around so its address changes between the move-in and move-out.

It's complicated enough to know whether this is even possible that we're leaning toward just abandoning the idea for now.

The double userdata still has some value, for no-allocation entrypoints (see CallCallback2 and CallCallback2_T in the gist).

**Comment by Kangz** [comment]
It seems it could be possible with placement new and friends. Maybe @amaiorano would know? Here we're trying to memcpy a non-trivially copyable lambda to an allocation managed by the wgpu runtime. But maybe it could be moved?

**Comment by kainino0x** [comment]
It would only be possible for us to move it in C++ if the C API gave us the space to write into. If we just pass a size and pointer to the C++ object, then C is the one actually moving it. So the question becomes whether you can move the data for a non-trivially-copyable object around without calling its move constructor. It seems likely no.

**Comment by kainino0x** [comment]
- KN: proposing having two userdatas because it’ll still be helpful sometimes
- CF: Would like to put everything in a struct
- KN: Planning to add an enum too, could go in the struct. But function has to be outside, or we need many struct definitions
- **Proposal: One struct type for each callback {mode, callback, userdata, userdata}**
- Even though it’s a little annoying to write in C

```cpp
// inline
f((WGPUBufferMapCallbackInfo){mode, callback, userdata, userdata2});

// out-of-line
WGPUBufferMapCallbackInfo info = {mode, callback, userdata, userdata2};
f(info);

// C++
f({mode, callback, userdata, userdata2});
```

**Comment by kainino0x** [comment]
Also discussed just having a single struct for {mode, userdata, userdata2} and putting the callback separately. But we thought this was slightly better and it doesn't matter a ton.

**Comment by kainino0x** [comment]
Moved the callback thing to a new issue so I can label it correctly. Better late than never :)

**Comment by kainino0x** [comment]
To finally return to the original topic...

webgpu.h meeting: Yes, we should add these macros. They seem better than any other options (like trying to define a `static`, calling a function like POSIX).

We would _like_ them to be well-typed to provide decent error messages to users. @rajveermalviya suggested the macro could be like `(WGPUAdapterProperties) { 0 }`. However I [tested this](https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyagA%2BudTkVjVEQJDqzTAGF09AK5smIaQDZyTgAyBEzYAHKeAEbYpCAArOQADuhKxPZMrh5ePv7JqXZCwaERbNGxCdbYtukiRCykRJme3n5W2DYFTLX1REXhUTHxVnUNTdmtSiO9If2lg3EAlFbo7qSonFxEAJ6J2Dg0ANSTpO62BwCCBwCkAOwAQgchRAfqVwDMD7cAIhfvd1dac4A85PA5sFghCAAN3QBEwC2u92BBxRFwOLB41zeP1uD2kiK%2Bf2RqMuLAATFiflBzgjcQd8d8Fn8DgB6FkHADyTHoW3R9Ho6AA7ntHkwDs4AJwS4HElHQ2Hw9E8ImA1EHeVwhHklVAm6EwFcJb0bhxfjeLg6cjobjOI4rNbYa5kt58chEbSGpYAa3iWkM3Gk/DYIDebwAdKHI1Ho/5zZbrVx%2BEoQH73RbDeQ4LAUNh1FV3CQKFQIPVgEpVMZ2iIkELza6MGxEgwWJ0K6F6NXax7yA2m4xYqhUEYTDwbloeD30I2GDEwuwNvxezPSByC53BXH%2BLmqudSGXuFu86haoRzfxBMIxBJODI5MJlGpNOnyPoyYZjGYLIYCJFk5AlugiSdMmXAALSTJg7xfKgEpaAcoEAOrYFCMRbEQSAhMA8EIUw6CgQ2HDCPw6AoaQpBwtgf4QEsSj2usBgQSEbZVjWG7cK6gqkCwiTsRmxpcKa5Cbla3C4EeBZkC8AAcvigb4%2BJDh%2BByjmGWhhpiEDOOQBz4MQklXM6PALPwaY6AsSxINgLA4LE1H%2BlwgbkMGoYRtGbmhrG3YJkmKZuh6SxZsgIDbqgElFtQpblpWHasXWi5Tn2LbpMxMVds%2BS79mgikjmOE4ZbO84HpO079quoixd2IW7vuiYBEeJ4hEVF6iOIki3s1D4aN2%2BhvO%2BJggOYpiWPQP5UQBQHpCB4FEJB2IwRK2HIah6GYcRpHkTgY3LKs9EToxTApeucXkJx3G8UaJpml5oniYW0myfJBzZVhKlqRpWk6YQd0GS6xl%2Bem5n2Y5znhu57lCddtXJqm/ner69lvFdz7ef9ZmZoggUQCgGA4LphaUNQdCMKwHC8XeLXXlIsgdSoXXPq%2BfWgKgBn/GSdxtB06SOEwLhuM0IC%2BH6QQzCUZRDHkaRCGM3iC0kKSS0wfSi/MHNVJ03SjHz2RxBKqvVEIGvTMUAzlMMPTS/EuuTD0Ssm/ENF0Rs2y7PsRxECcZyXHSoKvB8BK/B8MqAqC4KQjCmqIv8qokkqlKR/SBI6mqpIUlB6oQDS8cMnqTJ%2B2ynLcryEgCsKmCigcuFMNNxiYPUZfOCzjfRyipJvHHGdZwSucPPnXI8nyJciiE4qN2zPDKoCsrquHioYknqIarPZLz3KM9am8OrfMCfGXRDyM2qPDy0Ttjo/WSJmw%2BQlnWYMdk%2BnEfr8cDIag2DMZ7/GRXQ6jGaYzmt1kAJiWPcUV2xHTJhlJKQhDoVXSglZcaBhzAFHOOYqfYCqk1qvlFca5YGWiqiAoqIUGpnnJleNq1N5CdSfJafQE4kFoEPt%2BX88BxrAW4NNWa0FD5aDbohJapA0IYRMGtGIG1KKsO2g6EAb59owLShxLiPFeA7wEkjT%2BXAxL5juuoGSckFJIOUjcVS6l1QNzZizbSeN9LOjJH9Uynor5WRstQC6Dkgwv1cm/SMnl95Q18g4gKGN/7aMAcWSK8i2IqLQc2Vs0VwFwJKoMZ6KC8rwP7HOTB8Ukk4PKmlfBR5qogUPFUEhTV5DkJvJQ%2B8tMaF6B8IzRhFi2bMK2oBdhYEIJQWZs0u449FqkSEatK060KJbWPtI2RM0mLxNgYos6Ki3GCWEgmLRoUdF6Mes9IxJj3pMM%2BnpUgTo3h2IvgDNxz8XLeKjB/YiX8AmX3vo/bgiNbkiVqoEtx58nJSC0H6FZRVPnkFIqkBw0ggA%3D%3D) and it turns out not to be allowed in standard C++ 🙁:
```
<source>:5:13: warning: compound literals are a C99-specific feature [-Wc99-extensions]
    5 |     A a2 = ((A) { 4 }); // Only allowed in non-standard C++
```

`WGPUAdapterProperties { 0 }` is invalid in C and only becomes valid in C++ with C++11.

So I think to do this we'd need something like this ([full sample](https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyagA%2BudTkVjVEQJDqzTAGF09AK5smBpwBkCTNgAcp4ARtikIABMAOzkAA7oSsT2TK4eXgaJyXZC/oEhbOGRsVbYNrlMIkQspETpnt48ZRWp1bVE%2BcFhEQZKNXUNmc39HV2FxVIAlFbo7qSonFwApFEAzAQ0ANQ4dIGYEBbxHkrH7kpTy1oAgqtrW1ubW0cnZ0pby2u4nwAiW1FaHg8LRrXxXW7rB4PXYBbBbADqAHFVApTABJIJogAqplUACVcAAxNEADQgWKmWyx4LuUK28VILGAbBYWw4SiUTOwEFWUWcqwAQoKgbzLjdaVtyioaZCoTDAgjkaiMdjcQTiWSKTL7lCGUyWWzsByuTyonzBYKtm5MKLtQ8nJtteUnvLsAdzCIsT9nKYAGq4PEiNEAeSC5kpqwAbFHnqZPd6/QGg6HzB8vr8tjwAJw5wFg8Wy12KlHozE4/FE0nkynVu30xnM1nsznAbm85w520FtZS7B1otIksq8vqqta7sPPWNw3G1umvlW%2Bg2s1iiE9piEGg0m5EACe8Td2G2/VI7lsW2uHxiAsewi26k%2BN%2BWMT%2BtzWQu7ReupexxeVZbVSsyWuCNry2AB6AAqLYADp1DTP5IPArYtCvH5wT3A9di2E8zyILYnzAgJ8N3R80IIx9t2uYi2RYAIIAAN3QAhMFAj9LyhS9WQzb9h0om46RvUIEIvH9qXfCDkNwUhSDIR53hwIhsFsN1by2Dssy2YxMHUi0ogFEUBKhRjmNYrT%2BI4h4TJYylQgs590JuLgZnobgAFZ%2BG8LgdHIdBuGcHC5gWOE7j4cgiG0ZyZgAaxANytEMbhpH4NgQDWNYYPSrLspyyNyC8ny/K4fglBABKIu85zyDgWAUGwdRlPcEgKCoCBamAJRVGMcoRCQdAAHcvLCjA2HiBgWEqLrAnoXqBoK/gRrGxhIlQVAjBMHgYkBchFoYCIgnYJYFvQUa9tIYMmtmwbIvIerlOuUgOu4fg7tQapCC8/hBGEMQJE4GQ5GEZQ1E0SryH0KJDGMMwLEMAhQlKyAZnQeJKlKrgAFp%2BhtNYflQLNUIx%2BFsAYiJdyIJAAmALYiaYdAMZGjhhH4dBSZklijXgGYlCCxY%2BiID6pp6vrrt4fh%2BsZeJuD4Fz3M8m6itwBrUCauT1AADkjDHI2kLY1uhzMYhgrQYJ4LYIGccgtnwYg5NCqZ%2BAqnQphmJBsBYHBIggWWuGS8hUvSzKcuD9K8vm3znqsMrwsimYauQEBXtVlrqHazrupmkWhuO06jEmjOrvD3blrQfWNq25pi/2w7I6r87Lqzm7Xoep7itu5X3oCSPvtEcRJABnvgY0G79DWKGTBAcxTEseh4cR73fNR1J0axgXfnxzSiZJsmKaplm2dIDn5%2B53n/qsAWAiFzO5ul8XJdvn2PPyhXuCVxrmvvTXtd1svqc243Tbm0ttbQgH97aO1jj7P2AcMohxDs/MGRUSrRydlFcgsV4qJS4GseWiDI6oLjogeOEAUAYBwDbZqlBqB0EYKwDgt9Aa9z%2BlIWQg8VDDzBhDceoBUB6QFC0ZSlRHAbiGE0dWt0NzjB6CUSG2QUhCFEVIcRcjKhSKKL0M0AjbBtAGPUNwjQlFaMqO0OoajJiaNGIMfRwxxGWM6LCCYGiogn3mHzFY6wXRHlhO6aebw3irglE8F45w3hpm%2BLjf4gJgSgjrNCLxCpBz/lVBWDU1YqSxPrPqJsRoWxtjNPyfSwoeBdjXPaeg0oJxyniXCRJYlAKpPHKU3UDYDTNhNO2Phi5lzOLrA6Lc3ZnTbFdD4%2BMPp/SBhDGGUwEYojRlmbGUZiYJkplMGEjM2Zcw8HzE0gcSo6kpLHDWRpEopytJye0/JnYVxOnKX2SpuyhwAQOZqAJspTnZNnHkhc1oSl3D6VRTCh5jxEFPOeS8z4bw0QfBJByF57LrC/GJP8%2BzRzATYhBaCcERJIRQmhDC%2B4gU4RBXhAiV5IV3lIjCl8FF3xURoiyeiTEbJkvBHSLiIleJlgsoJLYwkeJiTIuBKSMk5IEAUtgJSKkdIBHUjmLSG5dKFP0oZSy5smVmRYNy4y6rbL2RfOCKqrkuBP3DkVApQp9KBVcSFdYUQIGVRduQN2HtegLwwQlI10C0qwLgblBBhVI6lXKrHaqRC6rK2TlQtqj107TULgw4uE1UhX3jWDOuaB1rAE2ttOuB16FtzrhdUQjcwbNxjZHV6ndPqMN%2Bv3Vh8gh6gx8voZoma0B8LhgjLmi80bcFXjjPGfCQQ02JmzcmlMTD7wiIfHAx9ZjWuiOfQWBcS1hQliwKWYtH64IDVwN%2BKsP4ay1jrPWmbDYALNhbDtIDbakA%2BLah2McHWu3dp7agUCUreqDr6rKYcX5tyDU%2B52ob4AkMThGyhrU04ptXTnJaSahAwZvmmk6S1ei/2zZXVDZ081HR2th5aRbU0%2BTLa3F6HcL7Vp7rW/69agbsKbXoEAsg228KVfw2eXakY9uXn27G68%2BFAhHdvUg46qYjrpgzPhWZ1YM1QxNKd7NZ3dp5guyG2NL4ruQ2u%2B%2BW6sEmv/fu5On9j0/zPf/E2l7zWCithQu2D77XOw/f7L9P7sr%2BpZoGlBkD0FxQ9dwHBHmI5twIT7O1LngQJVNfgnzbNkgOGkEAA%3D%3D)):

```c
#if defined(__cplusplus)
#  if __cplusplus >= 201103L
#    define WGPU_INIT_PREFIX(T) T
#  else
#    define WGPU_INIT_PREFIX(T)
#  endif
#elif defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
#  define WGPU_INIT_PREFIX(T) (T)
#else
#  define WGPU_INIT_PREFIX(T)
#endif

typedef struct A { int x; } A;
#define A_INIT WGPU_INIT_PREFIX(A) { /* .x = */ 0 }
```

**Comment by kainino0x** [comment]
webgpu.h meeting: we'll do the macro thing, but tweak it so we can wrap parentheses around the typed versions (Just In Case):

```c
#if defined(__cplusplus)
#  if __cplusplus >= 201103L
#    define WGPU_STRUCT_INIT_INCANTATION(type, value) (type value)
#    pragma message("C++11")
#  else
#    define WGPU_STRUCT_INIT_INCANTATION(type, value) value
#    pragma message("C++ old")
#  endif
#elif defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
#  define WGPU_STRUCT_INIT_INCANTATION(type, value) ((type) value)
#  pragma message("C99")
#else
#  define WGPU_STRUCT_INIT_INCANTATION(type, value) value
#  pragma message("C old")
#endif

typedef struct A { int x; } A;
#define A_INIT WGPU_STRUCT_INIT_INCANTATION(A, { /* .x = */ 0 })
```

[full sample](https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyagA%2BudTkVjVEQJDqzTAGF09AK5smBpwBkCTNgAcp4ARtikIABMAOzkAA7oSsT2TK4eXgaJyXZC/oEhbOGRsVbYNrlMIkQspETpnt48ZRWp1bVE%2BcFhEdFxSjV1DZnNAx1dhcV9AJRW6O6kqJxcAKRRAMwENADUOHSBmBAW8R5KJ%2B5K0ytaAIJr69vbW9vHp%2BdK2yvruF8AIttRLQ8Hhada%2Ba53DaPR57ALYbYAdQA4qoFKYRAAVABKCmcGNMAEkggT8UTnDcghibhiCQB5IIQIgAT3i2HI2wAbhJ3NhpttGSz4VyPLyIfdodt4qQWMA2CxthwlEoZdgIGsos41gAhbXA9VXW7i7blFRiqHQ2GBREotGYnF4wnE0lBcmU6l0hnM1ns4U8vm%2B7Bmh7QqUyuUK7BKlVqqIa7Xa7ZuTD6oOPJxbIPlZ6W7CHcyY37OUwANVwWJEHvMfLWADZay90RjCyWyxX6eZPt8/tseABOftA8GG80562oxv250kx2uqk0%2BkC72c7m8/mL1cBg2Q4Oh2XyxXK4Cq9XOfsp4frE2Bi8w7D7eHI8d23FT52z90Lr1s5ci/0r1OStKe4RlGR4xhqib0MmsZbvc6Y0GKtxfns2wDKQ7i2NsNyfDEWpPMI2zqF8eErDE/x3OsOoXqONyOiSY62tiL50W%2BFJzh6EA3OypF4QA9AAVNsAB06idv8/G8dsWg4b8W7IXeqFEOhmEkbh%2BFENsTLETJ2w6pRiE3AEGlygEEAcugBCYNWuEQhK2Hyt2tFEiSxG2dCeGhGJWEsdpvGSbgpCkGQTwfDgRDYLYub4dsp69tsxiYDF8ZRFqeq3BKZkWVZ8Wuel0KZZZfKhLldxkRCXCzPQ3AAKz8N4XA6OQ6DcM4qHzIs8L3Hw5BENoFWzAA1iA1VaIY3DSPwbAgOs6xCTN80LYtNbkPVjXNVw/BKCAo29Q1FXkHAsAoNg6gRe4JAUFQEC1MASiqMY5QiEg6AAO71d1GBsPEDAsJU92BPQT2vat/Cfd9jCRKgqBGCYPAxEC5BgwwERBOwyyg%2BgX3I6QtLnUDb19eQJ0RTcpC3dw/DE6g1SEPV/CCMIYgSJwMhyMIyhqJoe3kPoUSGMYZgWIYBChFtkCzOg8SVFtXAALQDMm6y/KgvbSbLCLYByERMkQSABMA2zq0w6Cy59HDCPw6Ba4FlmRvAsxKO1SwGArAT/Y9z0E7w/AvdK8TcHwlU1XVhPrbgp2oOdwXqAAHDWss1tI2zQwLPYxEJWhCTw/LOOy%2BDEMFXXTPwu06NMsxINgLA4JEEBB1wE3kFNM1zYtbczctINNRTVjbT1fWzIdyAgFTUeXdQN13Q9gOe%2B9GNY0Yf3T/jXdIxDaAp7D8PNGvKNoz3u843js%2BE1TpPkxtRMRzTAQ9wzojiJIrP3xzGiE/o6z8yYIDmKYlj0CLMWdcmpS1SDLeWRBFbK37IbDW1sdZ6xMJba2pBbZAIdk7FmVhIFu2Xifb25BfYsH9t7eutUVqh24OHM6F1CJxwTknTeBs4YZyzjnPOhBaFFxLgPeujdm6zXbu3Ch3N1qbT7qXfq5AhojTGlwdYIdRE90kYPRAQ8IAoAwDgfOF1KDUDoIwVgHAA703kEzJ%2BsgX4qDftzXmX9QCoGSlqFoEVKiOCYC4NwjQfAeImD0SIzRsgpCEMMJoCQkjBKYH4oovRRjlFcW0QY9QvEjBcbYRJ4w4STFidgjooSXZJOiVMHgGCFjO1WBsbMd44R5j/u8d4sFzTPFeBcd4nYfhKwBECEEYIAK3nvAxCczFnKsTdPOT0gofQrj5OuH8fo%2BmATDPuSMh5jyxk1ClXUPBzzbjTPQU0N4LTVKtI%2BRik4WIzjYh%2BCZS5NxzOvLskMQFwwHmjCeJxkFoJREacGeCmYAE7BzLUgsRZSzlkrKYasUQ6zQobCCls4L2ymHad2PsA4eBDkeaOU5QyHQjMuWMjiX4pm/jXF%2BP8v4AK7heSst56yzwwX%2BQcrFxyHw2lxa%2BAl7FPyTPuRSnkVLnnLNAmsiCSYdlwQ8RmQ0SFBQoTQhhDS2EeLqUItpUi5ESr3BoixQZz48VOi5dczi3E1ICWEqJbsEkpIyTknKhSCqVI4TwkZTS6qyK6S1bcV1JkmAFWyjxNyjx7JeSck6EqEoPKhp8pRbYfltgBSCqQEKuxsDhUiolAIMUYEJSSpslKaVsL5XMoVHK%2Bk8qPH9UVLVZVbj7SqlwchXd1obJ1ClNqZTOobCiDwva5dyCV2rr0YBMjRoNv4dNQRQiloiLWj3LaO0B4HTUcdCOY89HXTJlPAGK8TGI0xuDX6qR3Yz2BoTQ%2BaAYbADhgjQ%2BqNjGX0PrjUQ%2BDGpny3T3KmN86ZswfszKQlj5Cvy5o1fQzQr1oCccLUW9sQHS24BAqBjj81alBLAzW2tdb62QREVBOB0FzE7dEbBtMT27oIUQkhgc5FNsoVwahkdaGx3jonZOV606sOzhAVt2oOEF2Tfcb5vay4VyrjXagfDJqTtbtO%2Banc6PiMXX25d8ANEjzXboq6k8yP4I%2Bgen6S8d2vvnuDXoTCb0730xDe96N90LwiM%2B8jb6I7nxlpTa%2BOCf333MSzQD7NrEgb0CAWQEHkNtucQAmD4s4NgIQwrP4YWtnofgVhkwsDjamycb2GOpsD2/RwzbfDsHHZEb5q7JgOmz0Ub9iYshii530Y09HehrGmEcczlxnjKU%2BNcO7cXfufbJNN2k7Jhas7Lbzokbw6Rw0x3cAUeN7ul8VH1x7cNkEo1m3KOm9bZIDhpBAA%3D)

**Comment by kainino0x** [comment]
Dec 21 meeting

*   INIT structs with designated initializers (it doesn’t seem to be possible). Should we have “constructors” for common cases or anything..? (could be post-v1)
*   Only applies to the C API. C++ designated initializers get defaults (we’re pretty sure)
*   (Can’t think of any good solutions. Just init first then set the fields afterward)
*   **This is fine, leave as is. Only a problem with the C API.**
