### ISSUE TITLE
wgpuSwapChainGetCurrentTextureView() returns a texture view but GPUCanvasContext.getCurrentTexture() returns a texture

### ISSUE THREAD

**Issue by litherum** [webgpu-native/webgpu-headers#161]
wgpuSwapChainGetCurrentTextureView() returns a texture view but GPUCanvasContext.getCurrentTexture() returns a texture

Seems like these should probably return the same type?

**Comment by Kangz** [comment]
There's a longstanding issue to revisit the swapchain from WebGPU.h, and this issue is basically the same as #89 so I'll close this one in favor of it.

Note that webgpu.h swapchains are unfit to implement the canvas support for WebGPU in browsers. There are a lot more things beyond what swapchain provides that a browser would want to do. Instead I suggest that you add an extension in your private `WebGPUExt.h` to create a WebGPU texture from an IOSurface / CADrawable. That's what we did in Dawn/Chromium and what I expect Firefox to be doing as well.
