### ISSUE TITLE
Mark pointers that arent used to return any data from a function as const

### ISSUE THREAD

**Issue by Beyley** [webgpu-native/webgpu-headers#169]
This would aid in parsing the headers for code generation features, such as knowing when and when not to put the C# `in` attribute (as you cant do that for all pointers, as if the function is supposed to return data through that pointer you pass in, `in` makes no sense)

**Comment by kainino0x** [comment]
Most pointers should already have the correct constness. There are many cases where constness doesn't correspond with in/out-ness, though. Examples:

- WebGPU objects, e.g. `typedef struct WGPUDeviceImpl* WGPUDevice;`, are "opaque handles" and the pointers are non-const. In many cases methods operating on these modify the internal state of the object. It might be technically possible to have these handles be const pointers, and const_cast them out, but it doesn't really match the programming model. In C# bindings, these should not be pointer parameters.
- Userdata pointers, e.g. in `WGPU_EXPORT void wgpuBufferMapAsync(WGPUBuffer buffer, WGPUMapModeFlags mode, size_t offset, size_t size, WGPUBufferMapCallback callback, void * userdata);`, are inputs, but can't be const because we need to pass them non-const into the user's callback function, in this case `typedef void (*WGPUBufferMapCallback)(WGPUBufferMapAsyncStatus status, void * userdata);`.

I think C headers alone do not contain enough information generate good bindings for many other languages. A higher level metadata file more similar to [`dawn.json`](https://dawn.googlesource.com/dawn.git/+/refs/heads/main/dawn.json) would be more appropriate, and would probably make sense to "standardize" alongside `webgpu.h` (when we get to stabilizing it and documenting its API more deeply). Vulkan has [something similar](https://github.com/KhronosGroup/Vulkan-Docs/blob/main/xml/vk.xml), and I think many language bindings are generated from it.

**Comment by Beyley** [comment]
I had misread, so the original title of the issue is incorrect, they _are_ marked as `T const *` (descriptors are the main things i refer to), but perhaps this issue could be used to track a possible file like dawn.json or vk.xml? (parsers and generators for khronos xml files like vk.xml and gl.xml already exist, so it may be good to follow the structure of those?)

**Comment by kainino0x** [comment]
^ Filed as #207.
