### ISSUE TITLE
Versionned Releases?

### ISSUE THREAD

**Issue by hmaarrfk** [webgpu-native/webgpu-headers#243]
Hello, thanks for the amazing project!

I understand that versions are somewhat tricky to manage for headers.

However, in my packaging efforts at conda-forge, I feel like it would help keep track of compatibility between wgpu-native and this repo.

Not to mention, we have automated tooling that will bump versions for us, but not so much for git submodules.

Thank you for considering.

Best

**Comment by kainino0x** [comment]
We're currently working toward a stable release, so I won't be personally driving any numbered releases until we're at release candidates for 1.0.

@hmaarrfk could you explain more what you need this repository for? I assume wgpu-native maintains or generates their own webgpu.h which may not always be in sync with this one. If what you're doing is specific to wgpu-native, you should use theirs.

If it's really useful we could probably determine the correspondences with Dawn, wgpu-native, and Emscripten, but with the caveat that these implementations are not fully compatible yet. It would create some overhead for us.

For Dawn, every time we do a PR that syncs this with the current version generated by Dawn, that should be a known compatibility point. For Emscripten, we roll changes in from Dawn so they may not match with revisions in this repository. @rajveermalviya would know what revisions of this header wgpu-native supports.

**Comment by hmaarrfk** [comment]
Thanks for considering.

I understand it isn't really stable. I think I can work to simply "vendor" the headers a little better.
Usually that is pretty easy if the downstream libraries create a folder within the `include` directory to help keep things neat and tidy.

The current packaging strategy is:

1. Package webgpu-headers in https://github.com/conda-forge/webgpu-headers-feedstock/ 
2. Package up wgpu-native https://github.com/conda-forge/wgpu-native-feedstock/

Ideally users would be able to download the headers from one package, and the library from an other.

I could make my request to downstream (wgpu-native) to simply "install" things in a subfolder by default, then I could put their versioned file in there.

**Comment by hmaarrfk** [comment]
i guess fundamentally, the use case is to help clearly communicate to the user when they are trying to use different software that do not support the same version of this header at the same time.

Not sure if yo ucare about this. but it might be helpful.

**Comment by rajveermalviya** [comment]
Currently, wgpu-native has two headers: webgpu.h (in this repo) and wgpu.h (for specific extensions). We include webgpu.h as a [git submodule](https://github.com/gfx-rs/wgpu-native/tree/cf02ef3a28c92340483a0393505717bc66103d18/ffi) to a specific commit of `webgpu-headers` that we support.

I agree with @kainino0x that we won't have versioned releases for these headers until we reach v1 for webgpu.h. In my opinion, `webgpu-headers` shouldn't be considered a separate package until the standardization (v1) is complete because there may be (many) differences between the implementations.

If you want wgpu-native to include the header we target in a different way instead of the current git submodule approach, please create an issue there, and we can discuss it further.
