### ISSUE TITLE
Pass the WGPUDevice in the lost callback

### ISSUE THREAD

**Issue by austinEng** [webgpu-native/webgpu-headers#251]
Knowing the device in the lost callback is useful for embedders to handle cleanup when the device is lost.
This is particularly useful when the embedder keeps track of some other objects/allocations which are per-WGPUDevice.
It's convenient to use the WGPUDevice as a key in some mapping, but the problem comes when the device is lost and you want to remove the relevant entries.

Today, you can't easily get the WGPUDevice, even via the userdata because the lost callback is passed in the device descriptor before you actually have the WGPUDevice handle. You *can* do it through an unergonomic dance where you:
 1. make a separate allocation before requestDevice
 2. pass that allocation as the userdata in requestDevice and as the deviceLostUserdata
 3. set extraAllocation->device = device inside the requestDevice callback
 4. lookup userdata->device inside the device lost callback
 
It would be far nicer and useful if the WGPUDevice were passed directly in the callback.

**Comment by lokokung** [comment]
I agree with Kai that calling the callback with the device isn't too useful since the device is loss. Another alternative we could consider is guaranteeing that the device loss callback gets called even if requestDevice fails? (Not sure if there's any previous investigation about this?).

If we do that though, then we could just separately allocate an opaque key that we pass to the device loss userdata. Could be something as simple as just an uint at that point, and then we just clean it up in the device loss callback.

**Comment by austinEng** [comment]
context: https://chromium-review.googlesource.com/c/chromium/src/+/5049071/comment/503e71a5_25381de6/

I believe the motivation is that it's cumbersome to keep an opaque key in sync with the device, when you could use the pointer to the device directly (so long as you don't release its last reference).

**Comment by lokokung** [comment]
Actually, w.r.t to my previous comment... maybe it would be more ergonomic to actually call the device loss callback in the case of a requestDevice failure? Otherwise, users need to know and manually clean that up? 

But if we did do that, then I think it might directly conflict with passing the device in the device loss callback since it's very possible that we never created a device in the first place?

**Comment by kainino0x** [comment]
> (so long as you don't release its last reference)

`base::flat_map<WGPUDevice, ...>` is basically keying off a raw pointer, and this seems quite fragile to me since it breaks out of the usual ownership semantics that we use in C++ to provide safety.

I had the same idea as the comment in that CL, which is it would be preferable to use an ID that will be unique forever. For example the WGPUFuture that we are already getting from the RequestDevice call.

**Comment by kainino0x** [comment]
> `base::flat_map<WGPUDevice, ...>` is basically keying off a raw pointer, and this seems quite fragile to me since it breaks out of the usual ownership semantics that we use in C++ to provide safety.

Or I guess we could implement `operator<` for `wgpu::Device` and then it would be both a strong-ref and usable as a key type?

**Comment by lokokung** [comment]
> I had the same idea as the comment in that CL, which is it would be preferable to use an ID that will be unique forever. For example the WGPUFuture that we are already getting from the RequestDevice call.

This is also exactly what I imagined when I mentioned just passing an uint in the device loss callback.

**Comment by colinblundell** [comment]
Thanks for the discussion, all!

The use case in Chromium is that there are clients of Dawn/WebGPU where objects aren't 1:1 with Dawn Devices and hence need to cache state on a per-Device basis, that they need to know when they can and should drop. SharedImage backings are the concrete example in question, as seen on the CL that Austin pointed to. There's no need to do anything on the Device itself in the device lost callback, but just know which Device was lost to be able to drop the relevant state.

I totally agree that keying the map off the raw pointer is not what we would want to do. The issue is that we need to be able to look up entries in the cache by Device, and right now, it seems like having the cache be keyed by the Device itself is the only way to do that. A unique ID per-Device that is then also passed in the device lost callback definitely seems ideal to me for safely and ergonomically enabling this use case.

WRT the issue of not having the Device around if we call the device lost callback from within device creation: I think that it's OK to pass a sentinel value from the embedder's POV in that case, because they should be able to detect that something went wrong in the device creation itself and avoid ever propagating that device into any of the per-device state that would then later need to be cleared.

**Comment by colinblundell** [comment]
SGTM!

**Comment by kainino0x** [comment]
Loko raised this again around MapAsync. Here are some things to further discuss:

*   Passing the parent object into the callback is only really important for DeviceLost and UncapturedError because those callbacks have to be set up before the device object exists. (Pretty sure) we said we would pass the buffer to MapAsync as well. This is pretty useful in C because you’ll often want to call GetMappedRange and Unmap inside the callback.
*   But if we’re going to do that it would probably make sense to do the same thing for all other callbacks.
*   With improvements to Dawn’s C++ bindings to allow passing a lambda, it’s easy to capture the Buffer in the MapAsync callback, so it becomes not that necessary there.
*   To write out all the options, pass the object in:
    *   0\) For none of the events
    *   1\) Only for DeviceLost because of the ordering problem
    *   2\) For DeviceLost and MapAsync, for practical reasons
    *   3\) For everything for consistency:
        - Instance into RequestAdapter
        - Adapter into RequestDevice+RequestAdapterInfo
        - Device into PopErrorScope+CreatePipelineAsync
        - Queue into OnSubmittedWorkDone
        - ShaderModule into GetCompilationInfo

**Comment by Kangz** [comment]
Given what you wrote about the C++ lambda (and what other languages have), 1) seems the better solution and in the future we would add the parent object in each callback passed before the object exists.

**Comment by kainino0x** [comment]
April 25th meeting:

*   What happens if you pass nullptr for a callback that takes owning args?
    *   Leak?
    *   Disallow nullptr so we can’t leak?
        *   seems easy to just delete it for them though
        *   but there’s no point in passing no callback for things like createPipelineAsync
    *   Don’t create the owning ref so it doesn’t leak?
    *   Change all args to non-owning? (We had decided about this already but maybe worth considering. Also, this would make all the args consistent.)
        *   would make using it in C a little annoying. Get the object, then need to reference it in order to take it
        *   in c++ can we pass it as a reference so you can std::move it?
*   CF: weird tension between trying to design idiomatic C API and designing something good for bindings
*   AE:
    *   I think we should make all the callbacks nullable b.c. some of the callbacks can be nullable, and useful (like onSubmittedWorkDone).
    *   Then, we should make all the other callbacks nullable for consistency.
    *   also, if we are going to ASSERT it is non null - we have to do something in the implementation; may as well default it to something that’s not fragile
*   CW:
    *   Counterpoint - it doesn’t make sense to request an adapter if you didn’t want to do stuff with it.
    *   There’s two uses of pointers in C - do you want this null or not, and then you might need it for an indirection
    *   For the callbacks that return owning objects.. eh? \
I don’t think bindings will let you not pass a callback. They won’t have that optionality.
*   KN: **let’s do the conservative thing and disallow null - can always change it and open it up later**

**Comment by kainino0x** [comment]
> * **Yes let’s pass the WGPUDevice, but pass it as `WGPUDevice const*` (`wgpu::Device const&` in C++) so it’s clear you don’t own it**

Detail I don't think I thought about - when the device is null (e.g. CreationFailed) should the inner or outer pointer be null? I I think we sorta intended for it to be the inner one (inner one is nullable, outer one is non-nullable).

Would need to document that.

**Comment by kainino0x** [comment]
> I think we sorta intended for it to be the inner one (inner one is nullable, outer one is non-nullable).

Loko points out this works better for C++ because then the outer one can be a const reference `const&` which is non-nullable.
