### ISSUE TITLE
Consider having a "count" for all enumerate calls.

### ISSUE THREAD

**Issue by Kangz** [webgpu-native/webgpu-headers#252]
At the moment the `EnumerateFeatures` calls only take a pointer to the list of things to write. This is technically ok when the size of the list never changes, but:

 1 - In the future we might have list that change sizes, like for an `EnumerateAdapters`
 1 - Even for fixed-size lists, it is good hygiene in C APIs to always pass the size.

**Comment by kainino0x** [comment]
Dec 14 meeting:

*   CW: I implemented an EnumerateWGSLLanguageFeatures in Dawn. Don’t think this is upstream yet but I assume we want it in the instance.
*   CW: Problem with enumeration, say adapters: you call it once with null, it gives a count, you allocate your array, call it again - and the number of adapters in the system has changed. It may write past the end of the array. So probably need take count as an input in enumerate.
*   RM: … Adding count seems fine
*   **Add a count input. Still return a count output. The return count could be larger than the input count, so you know you didn’t get all of them.**

**Comment by kainino0x** [comment]
Just had a thought - I can't remember if we talked about this already, months ago - why don't we change this so you _don't_ need to make multiple calls? In the worst case, a call-twice API changes size every time you call it, so you need to call it in a loop until you've managed to get everything it's going to output. Which is awful because almost no one is probably going to actually write that loop.

Since we're going to break these anyway, should we refactor them to use FreeMembers instead?

```c
typedef struct WGPUAdapterFeatures { // non-extensible
    size_t featureCount;
    WGPUFeatureName const * features;
} WGPUAdapterFeatures WGPU_STRUCTURE_ATTRIBUTE;

WGPU_EXPORT WGPUStatus wgpuAdapterGetFeatures(WGPUAdapter adapter, WGPUAdapterFeatures * features) WGPU_FUNCTION_ATTRIBUTE;

WGPU_EXPORT void wgpuAdapterFeaturesFreeMembers(WGPUAdapterFeatures features) WGPU_FUNCTION_ATTRIBUTE;
```

Or possibly the same but merged with WGPUSupportedLimits (see also #260).

**Comment by eliemichel** [comment]
The worst case scenario is very unlikely, and afaik other battlefield tested APIs use this kind of call-twice API that lets the end user manage memory in their preferred way? I have no strong opinion here though, both options sound reasonable.

**Comment by kainino0x** [comment]
> The worst case scenario is very unlikely, and afaik other battlefield tested APIs use this kind of call-twice API that lets the end user manage memory in their preferred way?

It definitely is, but it probably will occasionally happen that a list changes once in a race with application code. The bad case is that they just miss the end of the list (because it racily got larger), the ugly case is that they have uninitialized data at the end of their array because it racily got smaller and we didn't write anything there).

Jan 11 meeting:

*   FreeMembers instead of double-call pattern?
    *   E.g. it returns a struct with a count and pointer, and FreeMembers takes that struct
*   FreeMembers is consistent with other things in the API. Good - would not want to invent something new.
*   Also, we already decided we needed to make a breaking change here, so no cost to making a breaking change.
*   **Yes, change these to FreeMembers**

Unfortunately I didn't have much time to put together the agenda (and we ran out of time anyway) so we didn't talk about #260.
