### ISSUE TITLE
Add WGPUAdapterProperties::driverVersion

### ISSUE THREAD

**Issue by austinEng** [webgpu-native/webgpu-headers#280]
Knowing this information has been useful for us in Chrome - blocklisting, workarounds, etc.

We could add a driverVersion field to adapter properties which contains a backend-dependent version. Driver versions can generally be communicated with a list of numbers:
 - 551.61.0.0
 - 23.3.62
 - 101.4972
 
Interpretation of them usually depends on what backend / OS you are running on. On MacOS, this number is essentially just the OS version. 

The alternative to this is to have separate chained structs for each backend, then it is slightly more typesafe and it tells you "this is the Vulkan driver version" or "this is the D3D driver version", etc.

Since we haven't cut a 1.0 stable header yet, could it be in the base struct?

```diff
typedef struct WGPUAdapterProperties {
    WGPUChainedStructOut * nextInChain;
    uint32_t vendorID;
    char const * vendorName;
    char const * architecture;
    uint32_t deviceID;
    char const * name;
    char const * driverDescription;
+   uint32_t* driverVersion;
+   uint32_t driverVersionLength; // alternatively, we could say the `driverVersion` is null-terminated
    WGPUAdapterType adapterType;
    WGPUBackendType backendType;
} WGPUAdapterProperties WGPU_STRUCTURE_ATTRIBUTE;
```

**Comment by kainino0x** [comment]
Adding it to the base struct seems fine (even in WGPUAdapterInfo which I think is going to replace WGPUAdapterProperties).
Unfortunately we can't guarantee the numbering scheme because different drivers use different schemes. I think Vulkan defines a particular one, but GL does not. Some numbering schemes say `5.10 > 5.2 = 5.02`, and others say `5.10 < 5.2 = 5.20`. We've seen mobile GL drivers where many different driver versions had the same number, and others where there was a revision hash in the driver version. On macOS I think it may even be possible to have two different 14.3.1s for example with different build IDs (23D60). Also iirc on Windows every driver has two version numbers - one from the vendor and one from Microsoft, and they don't always correspond 1:1.

Point is, if we're going to try to produce a driver version in this format, I think we would need to normalize them, and that may not really be feasible.

> ```diff
> +   uint32_t driverVersionLength; // alternatively, we could say the `driverVersion` is null-terminated
> ```

Probably not because 0 is a valid component (like in 551.61.0.0).

**Comment by austinEng** [comment]
So, do you think it would be better to just expose an opaque number on a vulkan-specific struct, an opaque number on a d3d-specific struct, and potentially nothing on MacOS? (app can go query the os version themselves)

**Comment by kainino0x** [comment]
Mar 14 meeting:

*   AE: Think conclusion is it’s probably not worth normalizing
*   KN: ~~Vulkan is normalized~~, think D3D version number is also normalized (but not e.g. the intel driver version which is a different number than the version of the d3d driver it provides)
    *   Vulkan is NOT normalized: “The encoding of driverVersion is implementation-defined.”
*   AE: There’s a webpage that tells you how to convert windows driver version to intel driver version \
https://www.intel.com/content/www/us/en/support/articles/000005654/graphics.html
*   KN: Could expose driver version as a string AND have extensions for backend-specific normalized driver ids
*   …
*   KN: If we normalize to integers, how would we handle mac build ids for example?
    *   AE: Maybe don’t handle them. Mac applications can just get that themselves
*   AE: Could also expose a bit that tells you how to interpret the number (1 . 2 3 or 1 . 23)
*   KN: Dawn will have to normalize anyway, but is normalizing something we want to impose on all implementations of webgpu.h?
*   AE: Would be silly if application has to re-encode the version number we normalized
*   AE: D3D driver version is a uint64
    *   Vulkan is uint32
*   KN: Vulkan is not normalized so we would have to report it as a single uint32, OR parse it per-vendor and re-normalize it.
*   **Do this in implementation extensions for now, maybe someday standardize a multi-implementation extension, but won’t add it to core struct.**

**Comment by austinEng** [comment]
Closing this since it's Dawn-internal for now. Can reopen if we want to make it common.
