### ISSUE TITLE
Consider adding WGPUPresentMode_Undefined

### ISSUE THREAD

**Issue by Kangz** [webgpu-native/webgpu-headers#289]
All enums have an `_Undefined` value but not this one. For consistency we should add it. And if we want `Fifo` to be the default mode, then that can be defaulted inside the implementation by treating `_Undefined` as an actual value, like we do in many other places.

**Comment by kainino0x** [comment]
May 23 meeting (sorry for delay):


*   AE: Is there a reasonable default?
*   KN/others: Yes, FIFO
*   **Yes, add a default which is FIFO.**
*   AE: Is there a case where what the user gets for the default needs to be told to them?
*   KN: No, we can make it always FIFO.

**Comment by Kangz** [comment]
Keeping open as we need to decide whether to renumber FIFO to 0 if it is a good default value.

**Comment by kainino0x** [comment]
I took bad notes but I am pretty sure when we said "Yes, add a default which is FIFO." we meant "Add Undefined=0 which defaults to FIFO", not "Renumber so FIFO is 0" because that would have been an unusual thing to do.

Could technically also "Add FIFO to the Init macro but don't add Undefined" but that would also be an unusual thing to do.
