### ISSUE TITLE
wgpuAdapterPropertiesFreeMembers is seemingly missing from header

### ISSUE THREAD

**Issue by PJB3005** [webgpu-native/webgpu-headers#304]
* this comment implies it should exist: https://github.com/webgpu-native/webgpu-headers/issues/266#issuecomment-1947242288
* Dawn seems to have it? Not familiar with Dawn's codebase though: https://dawn.googlesource.com/dawn/+/bc0f9d611b440eec30fe9c904daefc8dcf5eaa35/src/dawn/native/Adapter.cpp#230
* wgpu-native currently just permanently allocates the adapter info somewhere to avoid memory leak.

**Comment by kainino0x** [comment]
Oops, the conclusion of that issue was to replate both `wgpuAdapterRequestAdapterInfo()` *and* `wgpuAdapterGetProperties()` with `wgpuAdapterGetInfo()`. But we forgot to remove `wgpuAdapterGetProperties()`.

Let me reopen that issue so it will have the context and close this one. Thank you for the report!
