### ISSUE TITLE
How to support WGSL?

### ISSUE THREAD

**Issue by Kangz** [webgpu-native/webgpu-headers#35]
Now that WebGPU decided to ingest WGSL webgpu.h needs to be changed to reflect that. However I don't think that we want to remove the possibility of ingesting SPIR-V because it would make a lot of people in native very sad.

How about having webgpu.h support both? Either by putting both shading languages in `WGPUShaderModuleDescriptor` or alternatively by making `WGPUShaderModuleDescriptor` like `WGPUSurfaceDescriptor`, mostly an empty interface that only has extension structs?

**Comment by zoddicus** [comment]
Would being able pass both SPIR-V and WGSL in the same descriptor be useful?

**Comment by Kangz** [comment]
> Would being able pass both SPIR-V and WGSL in the same descriptor be useful?

Nope.

**Comment by kvark** [comment]
I agree that it's valuable to allow passing in SPIR-V binary directly here. We could shape this as an extension, but that doesn't mean that `WGPUShaderModuleDescriptor` needs to be an empty node: it could still carry a string, we'd just expect a NULL there.

**Comment by Kangz** [comment]
I can see a mode where an application might not want to ship the WGSL frontend of the compilers so Dawn would raise a validation error if the string is not NULL. That's probably fine.

**Comment by kvark** [comment]
So that would be native-only apps with SPIR-V toolchains? Good point... It's not a big dependency for us, but I agree that we may have people wanting that.

**Comment by zoddicus** [comment]
So it sounds like we want the descriptor to still contain the shader data. I think that means there is effectively 3 options:

1.  Convert `WGPUShaderModuleDescriptor`  to contain a string, and have an extension/different mechanism for passing in binary:
```
typedef struct WGPUShaderModuleDescriptor {
    WGPUChainedStruct const * nextInChain;
    char const * label;
    uint32_t codeSize;
    wchar_t const * code; // Using wchar_t, since it is likely we need something wider then ASCII
} WGPUShaderModuleDescriptor;

// Some sort of parallel SPIR-V based thing code path with its own descriptor and APIs.
```
2. Convert `WGPUShaderModuleDescriptor` to contain both a string and binary buffer, it is expected only one would ever be set.
```
typedef struct WGPUShaderModuleDescriptor {
    WGPUChainedStruct const * nextInChain;
    char const * label;
    uint32_t codeSize;
    uint32_t const * code;
    uint32_t textSize;
    wchar_t const * text; // Using wchar_t, since it is likely we need something wider then ASCII
} WGPUShaderModuleDescriptor;
```
3. Add a flag/enum to `WGPUShaderModuleDescriptor` to indicate the type of data stored in the descriptor, and just use a single buffer as a bucket of bits. The consumer of the descriptor would be responsible for checking `encodingType` and converting the buffer as needed.

```
typedef enum WGPUShaderEncodingType {
    WGPUShaderEncodingType_WGSL = 0,
    WGPUShaderEncodingType_SPIRV = 1,
} WGPUShaderEncodingType;

typedef struct WGPUShaderModuleDescriptor {
    WGPUChainedStruct const * nextInChain;
    char const * label;
    WGPUShaderEncodingType encodingType;
    uint32_t codeSize;
    uint32_t const * code;
} WGPUShaderModuleDescriptor;
```

I am personally preferable to something like 3), because 1) is going to create lots of parallel code/implementation details and is a relatively intrusive change and 2) is bit better but it is inflexible, slightly less efficient on space and more prone to programming errors.

For implementations that don't want to support some of the shader encodings, i.e. being SPIR-V or WGSL only, relatively early on in the stack they can check `encodingType` and reject any encodings that they don't support.

**Comment by kvark** [comment]
It would be nice to not deviate from the Web API too much. For programs built for the Web target, we should support a path that's not even capable of receiving a SPIR-V binary. For this reason, I think just exposing this as an extension makes most sense. The extension would say something like "if a chained SPIR-V structure is present, it takes preference over the original code, which can be NULL".

**Comment by Kangz** [comment]
I was thinking of something like the following:

```c
enum WGPUSType {
  // ...
  WGPUSTypeShaderModuleSPIRVDescriptor,
  WGPUSTypeShaderModuleWGSLDescriptor,
  // ...
};

typedef struct WGPUShaderModuleDescriptor {
    WGPUChainedStruct const * nextInChain;
    char const * label;
};

typedef struct WGPUShaderModuleSPIRVDescriptor {
    WGPUChainedStruct const * nextInChain;
    WGPUSType sType;
    uint32_t codeSize;
    uint32_t const * code;
};

typedef struct WGPUShaderModuleWGSLDescriptor {
    WGPUChainedStruct const * nextInChain;
    WGPUSType sType;
    char * const code; // UTF8 encoded.
};
```

But it's a bit overkill for just two possibilities maybe.

**Comment by kainino0x** [comment]
I prefer option 1 over the double-extension thing. It matches the web api more closely and is not any more annoying to use for SPIR-V users in native.
