### ISSUE TITLE
Missing valid empty state for enums

### ISSUE THREAD

**Issue by menduz** [webgpu-native/webgpu-headers#367]
Hello there, I'm developing a code generator for Zig, and int-based-enums are required to have a valid empty state for the value 0. Since https://github.com/webgpu-native/webgpu-headers/commit/61dd4987fb3b1d0fb9240c8065ed753fd0b33062 there are no more 0 values in enums. For the moment, I'm adding back a manual ".undefined = 0" to all my enums not starting with 0.

Feel free to close this issue after reading, its intent is to provide a heads up

**Comment by kainino0x** [comment]
Thanks for the note! We are reserving 0 for `undefined` in all enums anyway, and it makes sense for it to be nameable in some languages (C can still sort of use these values without naming them since they're the zero-init values). Maybe we'll decide we want to make it nameable in C too someday, but for now it's not really necessary.
