### ISSUE TITLE
WGPU_WHOLE_SIZE should probably be WGPU_REMAINING_SIZE

### ISSUE THREAD

**Issue by Kangz** [webgpu-native/webgpu-headers#44]
When we introduced this constant, defaulting the size of the `GPUBindGroupEntry` in the JS API made it take the whole buffer, but we then changed it to be the rest of the buffer. The semantic is different and the name should probably be changed.

**Comment by kainino0x** [comment]
actually...
unmarking has-resolution, because I don't think a rename is actually worthwhile here. If you're specifying `offset, WGPU_WHOLE_SIZE` there's only a tiny ambiguity about what that means:
- is it [offset, end)
- or [offset, offset + total size) which would always be invalid so it would be silly

My proposal is just close this and keep the name.

**Comment by Kangz** [comment]
Sounds good, let's just close.
