### ISSUE TITLE
Proposal: add API for consume shader IR directly (DXIL, Metal IR, SPIRV...).

### ISSUE THREAD

**Issue by munrocket** [webgpu-native/webgpu-headers#459]
**Use cases**
The idea is to use [Slang](https://shader-slang.com/slang/user-guide/targets.html) or [Tint](https://dawn.googlesource.com/tint) for creating ahead-of-time shader modules on Mobile/PC without too much effort (forking dawn/wgpu). Looks like this is the main reason why some engines not choosing dawn/wgpu.

Related: gpuweb/gpuweb/issues/3175

**Comment by eliemichel** [comment]
AFAIK the standard `webgpu.h` API does not intend to expose features that are not available in the JavaScript Web API, and loading backend-specific shader format directly is not going to be a feature of the Web API (it defeats the strong goal of the Web APIs to be portable -- the issue you link does not mention loading backend-specific shader IR, rather a binary version of WGSL).

Nonetheless, this C native API is designed to be **extensible with native-specific features**. These are by definition not part of the `webgpu.h` header, but individual implementations like Dawn or wgpu-native do have many of them already. And as a matter of fact, they both **already have an extension to load SPIRV**.

So the **good news** for your use case is that the standard is not a blocker, all you need is to ask the devs of your implem of WebGPU (dawn or wgpu-native) to expose an extension for the IR of your choice (better even, you can contribute yourself ofc ^^).

(Of course this only works if you target a native development, otherwise you need to stick with the standard Web API, but anyways you would have difficulties in even figure our which shader IR the client needs if you're running in the Web browser.)

**Comment by kainino0x** [comment]
FWIW many native applications actually want to cache pipelines on disk, which bypasses createShaderModule entirely after first load.

We don't have anything standard for this yet, but Dawn for example does have some capabilities for this - IIRC platform hooks you can set up to let it do the pipeline caching itself.
