### ISSUE TITLE
Signaling allocation failure for buffers with `mapAtCreation==true`

### ISSUE THREAD

**Issue by austinEng** [webgpu-native/webgpu-headers#57]
Following [gpuweb#872](https://github.com/gpuweb/gpuweb/issues/872), we need a way for buffer creation with `mapAtCreation==true` to fail.

I can think of a couple options, none of which I love, so I would be open to other ideas.

## Option 1
`wgpuDeviceCreateBuffer` returns `nullptr`. This would match the JS API best (throws an exception, and the `GPUBuffer` would be `undefined`), but has the unfortunate consequence that it is the only part of the C API that returns something null.

## Option 2
`wgpuDeviceCreateBuffer` works, but `wgpuBufferGetMappedRange` returns `nullptr`. This would be a little more natural as `wgpuBufferGetMappedRange` is what gives you the pointer, and developers would be more used to checking if a `void*` is non-null. The drawbacks are as follows:
 - It would not match the JS API. You would still get back a `WGPUBuffer` when using the C API.
 - Implementing it would involve some magic in the WASM to JS layer (ex. Emscripten) to `try {} catch {}` around the call to `wgpuDeviceCreateBuffer` and then give back some proxy object which does nothing on the other methods and return `nullptr` from `getMappedRange`

Thinking about this after I wrote it, Option 2 may have way too much magic involved with other places a `WGPUBuffer` is used like making bind groups and stuff. *Maybe* it is workable if the implementation reserves a handle for the "not actually allocated" `WGPUBuffer` object but it doesn't seem like a good idea. Only Option 1 looks feasible.

**Comment by kvark** [comment]
Agreed, Option 1 is fine. Thank you for raising this!

**Comment by austinEng** [comment]
@Kangz any thoughts?

**Comment by Kangz** [comment]
Both have large drawbacks. Option 1 is unfortunate because it means that applications have to check all buffer creation if they want to do perfect error handling. It is relatively simple to implement in dawn_wire by forcing the creation of an error buffer if CreateBuffer return nullptr. Actually this gives a good implementation of Option 2 in WASM -> JS: if JS return an exception, then the shim can create an error buffer, and use it instead.

I have a slight preference for 2, so that people don't have to check all buffer creations, and only GetMappedRange. But no super strong opinion.

**Comment by kvark** [comment]
The contract is that only buffers with `mapAtCreation == true` could return null, so the users are safe to omit that check and not expect a NPE for other buffers.

**Comment by austinEng** [comment]
I think Option 2 would be nicer to use, but there are in the WASM->JS layer which may cause unexpected results for programs that are invalid. In native, they would get an error buffer, and could successfully use that to create (invalid) bind groups. In JS land, their buffer would be `undefined` and passing that as a `GPUBindGroupEntry` would raise an exception because`GPUBufferBinding.buffer` is required. Similar concerns with `copyBufferToX` and `copyXtoBuffer`.

Maybe this is fine because it will only happen if a native app decides to go on without handling the error. Also, the issue with the error buffer mechanism is that it may not be discoverable. As far as I can understand, in WebGPU, we are not inserting an OOM error or validation error in this case -- only throwing an exception. So webgpu-native doesn't have a way of finding that it's an error until trying to use the buffer later.

Some more ideas..

Option 3:
-  WGPUBufferDescriptor has a `bool* mapAtCreationSucceeded` which the implementation writes into to set the success status. In native, it is a validation error to pass nullptr here. The browser implementation would always specify it for WebGPU. This way, native is forced to provide it, and has a synchronous signal that something failed. Then, the returned `WGPUBuffer` is never null, and the app can check failure by looking at `mapAtCreationSucceeded`.
 - Still has problems where native has an error buffer, and JS has `undefined`, but the app has something else to check.

And now, Option 4:
 - Like Option 3, but more drastic. Split `createBuffer` into a `createBufferMapped` variant (again). `createBufferMapped` returns some opaque object that you must check success on before Acquiring the `WGPUBuffer` it wraps.
 - Still has problems where native has an error buffer, and JS has `undefined`, but now the app is forced to check that the buffer is was an error before deciding it wants to continue using the error buffer anyway.
 - Alternatively this variant could not give you an error buffer -- acquiring the buffer asserts that the status was success. So I guess it's a fancy `Maybe<T>` wrapper that doesn't let you get null (in debug)

Option 5:
 - Split `createBuffer` and `createBufferMapped`. Just return nullptr from `createBufferMapped` if it fails. The benefit here is that it's more clear that one of them is synchronously fallible and one is not.

**Comment by doug-moen** [comment]
Option 1, return a null pointer when a buffer allocation fails, is idiomatic C. (Just look at `malloc`, `fopen`, and many other standard C library functions, which return `NULL` on error.) It's also simpler than all the other proposals.

The assumption is that application programmers will be using the C API directly. But that we can't rely on the standard C idiom of returning a null pointer on failure, because it's too easy to miss adding the error check. As if developers who choose to code in C need to be protected from C idioms.

I think that, instead, the common case will be that the raw wgpu API will be wrapped in some higher level framework, and that app programmers will in most cases be using the framework. That will be true when wgpu bindings are created for high level languages. And it will be true for the many graphics apps and libraries that use an app-specific portability layer for performing graphics operations.

I think a more important consideration is whether the framework or library or language binding calling `wgpuDeviceCreateBuffer` can determine if the allocation has failed, so that it can take immediate action (eg, like throwing an exception) if appropriate. This echos what @austinEng said:
> The issue with the error buffer mechanism is that it may not be discoverable. As far as I can understand, in WebGPU, we are not inserting an OOM error or validation error in this case -- only throwing an exception. So webgpu-native doesn't have a way of finding that it's an error until trying to use the buffer later.

This point seems like a good argument for the simplicity of option 1.

**Comment by Kangz** [comment]
> Option 1, return a null pointer when a buffer allocation fails, is idiomatic C. (Just look at malloc, fopen, and many other standard C library functions, which return NULL on error.) It's also simpler than all the other proposals.

The problem is that it clashes with the rest of the API that uses the Maybe monad for handling errors. So in even if it is idiomatic to check for nullptr in C, this would be the only place in the API in which you need to do that for object creation. You already need to do it for `GetMappedRange` that returns `nullptr` on failure, for example because of a validation error. So it would be nice to put it there.

> I think that, instead, the common case will be that the raw wgpu API will be wrapped in some higher level framework, and that app programmers will in most cases be using the framework.

Sure but the hope is that the accessibility of the WebGPU API will lead to many such frameworks and bindings, and we should pay attention to the framework's developer experience too.

> think Option 2 would be nicer to use, but there are complexities in the WASM->JS layer which may cause unexpected results for programs that are invalid. In native, they would get an error buffer, and could successfully use that to create (invalid) bind groups. In JS land, their buffer would be undefined and passing that as a GPUBindGroupEntry would raise an exception becauseGPUBufferBinding.buffer is required. Similar concerns with copyBufferToX and copyXtoBuffer.

> The issue with the error buffer mechanism is that it may not be discoverable. As far as I can understand, in WebGPU, we are not inserting an OOM error or validation error in this case -- only throwing an exception. So webgpu-native doesn't have a way of finding that it's an error until trying to use the buffer later.

That's not an issue if we synthesize an error buffer along with an OOM error. That's easy to do.

**Comment by kainino0x** [comment]
Given it almost doesn't make sense to allow fallible allocations with mapAtCreation (see comment upstream), maybe we should change it upstream so that it returns an invalid buffer and getMappedRange fails instead. This would be option 2, but change upstream to match it.

**Comment by Kangz** [comment]
There's also the question of what happens if the following happens:

 - The buffer is mapped (with `mappedAtCreation` or `mapAsync`).
 - The device is lost.
 - `GetMappedRange` gets called.

In all APIs I think we have the guarantee that mapped pointers are still valid when the device is lost (because it can happen racily with the application using it). I think that to allow applications handle errors and device loss gracefully, `GetMappedRange` should as much as possible try to return a valid, correctly sized pointer. Then on CPU OOM for `CreateBufferMapped` it can return nullptr, which is option 2).

I'll go ahead with that variant in Dawn and we can always modify it later if we need to.

**Comment by kainino0x** [comment]
@austinEng and I discussed this today and we didn't really see any good way to return a WGPUBuffer in this error case, because of WASM (options 2 and 3). We'd have to fake it, and then fake failure of a bunch of things that fail downstream (like createBindGroup, etc)

Between options 1/4/5, we preferred 1 for simplicity relative to the JS API. The main downside of 1 is that it will make the signature of CreateBuffer always return a nullable WGPUBuffer regardless of whether it needs to be nullable, but we decided this is fine because higher level language bindings are always free to split it into two methods similar to options 4/5.

AFAICT, option 1 is what we currently implement in Dawn's wire. (I think Dawn-native is option 2? but it's kind of complicated to read.)

Tentatively marking resolved
