### ISSUE TITLE
How to represent "undefined" in bytesPerRow/rowsPerImage?

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#69]
The obvious choices are `0` and `0xFFFF'FFFF`. Zero is nice because it's the default in C, where you can't specify other default values.

The problem with `0` is that you can't implement all of the validation behind the C API: `undefined` can be valid when `0` would not be valid. In order to implement the JS API on top of the C API, you have to treat all `0`s as `undefined`s in C, then implement additional validation in front of the C API to reject `0`s if they wouldn't be valid.

The problem with *either* is that you're narrowing `2**32+1` values (`uint32_t` + `undefined`) into `2**32` values (`uint32_t`). However in practice `0xFFFF'FFFF` is (probably) never a valid value for either one, so you can implement the JS API in front of the C API a bit more simply: just `if (value == UINT32_MAX) { injectDeviceError }`.

Alternatives are:
- `0`
- `UINT32_MAX`
- `uint32_t* bytesPerRow` (gross)
- `bool hasBytesPerRow; uint32_t bytesPerRow;` (also gross)
- `uint64_t bytesPerRow;` or `int64_t bytesPerRow;` (eh)
- Change rules in JS
- ?

**Comment by kainino0x** [comment]
BTW, if we have any other places in the API where we use `UINT32_MAX` (or `size_t(-1)`), JS-on-C implementations have to make sure they don't transform a `f64(2**32)` into the special value, and catch it instead. It's okay with `UINT64_MAX` because it's not representable as JS `number`.

**Comment by Kangz** [comment]
In this specific case isn't `undefined` for `bytesPerRow` / `rowsPerImage` the same as setting an arbitrary large value? We could go with a solution that sets stupidily large numbers. I agree that it would be best for the default in C to match what happens with the default in JS but that it might require some ugly workarounds in some cases.

**Comment by kainino0x** [comment]
No, `undefined` can be valid when either `0` or huge numbers would be invalid.

**Comment by kainino0x** [comment]
- `bytesPerRow` `undefined` is valid when `0` is invalid: `width > 0 && height <= 1 && depth <= 1`
- `bytesPerRow` `0` is valid when `undefined` is invalid: `width == 0 && (height > 1 || depth > 1)`

and similarly for `rowsPerImage`.

Possible solutions:
- Change JS to allow `0` whenever `undefined` would be valid.
- Change JS to allow any value whenever `undefined` would be valid. <- I think @kangz is in favor of this one?
- Change JS to disallow `bytesPerRow` or `rowsPerImage` of`UINT32_MAX`. (Is this even valid in practice? `rowsPerImage` of `UINT32_MAX` requires >256GiB buffer allocation, but `bytesPerRow` of `UINT32_MAX` only requires >4GiB.)
- Change C to have a pointer, extra boolean, or extra bits (int64/uint64). <- I think I'm in favor of this one. With some minor ugliness we could even do this in Dawn without changing `webgpu.h`.

FYI I tried implementing a version where C `0` is a union of JS `0` and `undefined`; that is, C `0` is valid any time either JS value would be valid. Here's what validating JS in front of C looks like:
https://chromium-review.googlesource.com/c/chromium/src/+/2504584/2/third_party/blink/renderer/modules/webgpu/dawn_conversions.cc

**Comment by kainino0x** [comment]
Actually, since there are invalid values of bytesPerRow (`% 256 != 0`) and of rowsPerImage (huge values), we could even do some magic in Dawn's webgpu.h implementation without any extra extensions or fields.....

**Comment by kainino0x** [comment]
alternative argument: should we leave C API surface open for bigger bytesPerRow/rowsPerImage values? The underlying APIs don't support it, but otherwise I don't see any reason you couldn't theoretically support larger values. Especially if we get sparse buffers, I think.

**Comment by Kangz** [comment]
> Change JS to allow any value whenever undefined would be valid

Yeah I'm in favor of this one.

My understanding is that previously `rowsPerImage` and `bytesPerRow` had to always have valid values even if they were never used, which was annoying. So the idea was to allow not specifying them when they aren't used and make that valid, that has value because it reduces the mental overhead since `rowsPerImage` can be completely forgotten until you do a copy with `depth > 1`.

However I don't think there's a lot of value, or any, in validating `bytesPerRow` and `rowsPerImage` are bigger than the corresponding copy size if set. At least for `bytesPerRow`, as soon as you start doing a 2D copy, it will need to be aligned to 256 in addition to being aligned to the block byte size. So I think the following validation would be enough and with the least mental overhead (with both values defaulting to 0):

- `bytesPerRow` must be aligned to the texel size.
- if `copySize.height > 1 || copySize.depth > 1`:
  - `bytesPerRow` must be a multiple of 256.
- if `copySize.depth > 1`:
   - `rowsPerImage` must be bigger than `copySize.h`.

**Comment by kainino0x** [comment]
Opened draft https://github.com/gpuweb/gpuweb/pull/1194

**Comment by kainino0x** [comment]
Resolved, we think: `0` <=> `0` and `undefined` <=> `UINT32_MAX`.

**Comment by kainino0x** [comment]
This was done forever ago, not sure why it's still open.
